name: Sync to ReadMe

on:
  push:
     branches:
      - master
      - test
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Map branch name to environment name
      id: get_env
      env:
        README_VERSION: v2.0
        README_API_ID_MAIN: ${{ secrets.README_API_ID_MAIN }}
        README_API_ID_BETA: ${{ secrets.README_API_ID_BETA }}
        README_API_ID_ALPHA: ${{ secrets.README_API_ID_ALPHA }}
      # get readme_api_id and readme_api_version from https://dash.readme.com/
      run: |
        REF=${GITHUB_REF##*/}
        echo running on branch ${REF}
        if [[ "$REF" == "master" ]]
        then
          echo "##[set-output name=readme_api_id;]$(echo $README_API_ID_MAIN)"
          echo "##[set-output name=readme_api_version;]$(echo $README_VERSION)"
        elif [[ "$REF" == "test" ]]
        then
          echo "##[set-output name=readme_api_id;]$(echo $README_API_ID_BETA)"
          echo "##[set-output name=readme_api_version;]$(echo ${README_VERSION}-beta)"
        elif [[ "$REF" == "dev" ]]
        then
          echo "##[set-output name=readme_api_id;]$(echo $README_API_ID_ALPHA)"
          echo "##[set-output name=readme_api_version;]$(echo ${README_VERSION}-alpha)"
        else
          echo "Invalid branch"
          exit 1
        fi

    - uses: readmeio/github-readme-sync@1.0.2
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}' # DON'T MODIFY--Allows us to get the contents of your spec file
        readme-api-id: '${{ steps.get_env.outputs.readme_api_id }}'
        api-file-path: 'bridge-api.json' # path to API spec file
        readme-api-key: '${{ secrets.READ_ME_API_KEY }}' # ReadMe API key 
        readme-api-version: '${{ steps.get_env.outputs.readme_api_version }}'